#!/usr/bin/env node

/**
 * Module dependencies.
 */
const app = require('./server.js');
const debug = require('debug')('test:server');
const https = require('https');
const http = require('http');
const fs = require('fs');

const port = normalizePort('80');
const portSecure = normalizePort('443')

/**
 * Create HTTPS or development server.
 */
const httpsServer = https.createServer({
        key: fs.readFileSync('/etc/letsencrypt/live/cmrnw.com/privkey.pem'),
        cert: fs.readFileSync('/etc/letsencrypt/live/cmrnw.com/fullchain.pem')
    }, app);

const httpServer = http.createServer(app);


/**
 * Listen on provided port, on all network interfaces.
 */
httpsServer.on('error', onError);
httpsServer.on('listening on port ' + port, onListening);
httpsServer.listen(portSecure);

httpServer.on('error', onError);
httpServer.on('listening on port ' + port, onListening);
httpServer.listen(port);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
    const port = parseInt(val, 10);

    if (isNaN(port)) {
        // named pipe
        return val;
    }

    if (port >= 0) {
        // port number
        return port;
    }

    return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
    if (error.syscall !== 'listen') {
        throw error;
    }

    const bind = typeof port === 'string'
        ? 'Pipe ' + port
        : 'Port ' + port;

    // handle specific listen errors with friendly messages
    switch (error.code) {
        case 'EACCES':
            console.error(bind + ' requires elevated privileges');
            process.exit(1);
            break;
        case 'EADDRINUSE':
            console.error(bind + ' is already in use');
            process.exit(1);
            break;
        default:
            throw error;
    }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
    const addr = server.address();
    const bind = typeof addr === 'string'
        ? 'pipe ' + addr
        : 'port ' + addr.port;
    debug('Listening on ' + bind);
}
